"""संक्षारण — MP Board Class 12, CHE-C2-LA-02.

Timed against the real HeyGen clip. `projects/sanksharan/timing.json` holds one
cue per spoken line, anchored to word-level transcript timings, so each caption
is up exactly while it is spoken and the render ends with the audio.

House rules this scene follows:

  · The opening line shows a QUESTION CARD instead of a caption — the question
    left-aligned between the top edge and the presenter, then its weightage and
    years right-aligned on one level beneath it. Captions begin on line two.
  · Captions are the only running text. Everything else is a diagram, an
    animation, a formula, a derivation, or a single very important point. Text
    that merely repeated the caption has been removed.
  · Captions are styled — larger, with the load-bearing words in colour.

Accuracy, from `accuracy_brief.md`: rust is dull reddish-brown and grows from
patches, never a smooth skin; impurities are specks INSIDE the metal; in
galvanisation the zinc is consumed while the iron survives; in electroplating
the object is the cathode on the negative terminal.
"""
from manim import *  # noqa: F403
import json
from pathlib import Path as _Path

import numpy as np

from src.manim_helpers import ThemedScene, norm_point, register_fonts, ui_font

# --- palette --------------------------------------------------------------- #
INK    = "#FFFFFF"
DIM    = "#B9C6DC"
IRON   = "#9AA6B2"      # clean iron: grey, metallic
RUST   = "#A6552B"      # reddish-brown, dull
RUST_L = "#C2703A"
ZINC   = "#8FA8BE"      # bluish-grey
COPPER = "#4E9E7A"      # copper corrodes GREEN, never brown
PAINT  = "#3E7CB1"
GOLD   = "#FFC15C"
WARN   = "#FF7B6B"
OK     = "#7CE0B0"
AQUA   = "#8FD3F4"

# --- typography ------------------------------------------------------------ #
# Khand Bold: a condensed Devanagari face, so more words fit per line at a
# given size and the caption stays out of the stage's way.
FONT = "Khand"
FONT_W = "BOLD"

# --- layout ---------------------------------------------------------------- #
# Three bands, and nothing is ever placed by eye. The caption owns the top, the
# stage owns the middle, the presenter owns the bottom. `place()` guarantees a
# block fits inside the stage — that is the permanent fix for the overlapping
# figures: it is impossible to place something taller or wider than its band.
CAPTION_SIZE  = 36
CAPTION_W     = 0.88
CAPTION_TOP = 0.105
STAGE_TOP, STAGE_BOT = 0.225, 0.545      # ends above the presenter's head
CAPTION_GAP = 0.28                       # clear space under the caption
STAGE_W = 0.84                            # inside the plate's border art

# ASSET_ROOT is defined by the composed header (see scene_codegen.compose_file).
TIMING = json.loads(
    (_Path(ASSET_ROOT) / "projects/sanksharan/timing.json").read_text(encoding="utf-8"))
# One caption LINE per entry, each anchored to the transcript word that starts
# it. A whole sentence held on screen while only its first half is being spoken
# reads as out of sync even when the sentence itself is timed correctly.
LINES = json.loads(
    (_Path(ASSET_ROOT) / "projects/sanksharan/lines.json").read_text(encoding="utf-8"))
CLIP_END = 126.93

# Generated by src/concept_images.py — transparent PNGs, cached by prompt hash.
# Used only where the appearance of a real object is the teaching content;
# equations, graphs and apparatus stay as Manim vectors.
IMAGES = {
    # Real alpha: generated on a white sweep and cut out (see concept_images).
    # The galvanised sheet is deliberately absent — it is a full-frame texture,
    # so there is no background to cut and it composites as a hard rectangle.
    # Textures stay as drawn shapes; images are for objects with a silhouette.
    "rusty_nail": "projects/sanksharan/images/rusty_nail_d30a33a055c17f95.png",
}
# Render only the first N cues when TEST_CUES is set, so a layout change can be
# reviewed in seconds instead of waiting out the whole clip.
import os as _os
TEST_CUES = int(_os.getenv("TEST_CUES", "0")) or None

# Words worth the eye landing on. Matched longest-first so "विद्युत् प्लेटिंग"
# wins over "विद्युत्".
HILITE = {
    "संक्षारण": RUST_L, "जंग": RUST_L, "अवांछित": RUST_L,
    "धातु की प्रकृति": WARN, "अशुद्धियाँ": GOLD, "वातावरण": AQUA,
    "विद्युत् प्लेटिंग": OK, "समर्पित बचाव": OK, "गैल्वेनीकरण": OK,
    "रोधिका": OK, "जिंक": ZINC, "लोहे": IRON, "लोहा": IRON,
    "क्रियाशील": WARN, "नमी": AQUA, "गैसों": AQUA, "गैसें": AQUA,
    "तीन कारक": GOLD, "तीन उपाय": OK, "स्क्रीनशॉट": GOLD, "उन्नति": GOLD,
}


class _StopScene(Exception):
    """Ends a short test render cleanly."""


def _y(t: float) -> float:
    return norm_point(0.5, STAGE_TOP + t * (STAGE_BOT - STAGE_TOP))[1]


class Sanksharan(ThemedScene):
    CAPTION_MODE = "narration"

    # ------------------------------------------------------------------ #
    def hindi(self, text, size=CAPTION_SIZE, color=INK, weight=FONT_W):
        return Text(text, font=FONT, font_size=size, color=color, weight=weight)

    # --- the layout guard ------------------------------------------------ #
    def stage_box(self):
        """(centre, width, height) of the stage band in scene units.

        The top is not a constant. A caption that runs to three lines reaches
        lower than a one-line caption, and a fixed STAGE_TOP let the two
        collide; the stage starts below whatever the caption actually occupies.
        """
        top = norm_point(0.5, STAGE_TOP)[1]
        bot = norm_point(0.5, STAGE_BOT)[1]
        if getattr(self, "caption_mob", None) is not None:
            top = min(top, self.caption_mob.get_bottom()[1] - CAPTION_GAP)
        return np.array([0.0, (top + bot) / 2, 0.0]), config.frame_width * STAGE_W, top - bot

    def place(self, mob, y=0.5, pad=0.94):
        """Fit `mob` inside the stage band and put it there.

        Everything on the stage goes through this. A block can no longer be
        taller or wider than the band, so it cannot collide with the caption
        above or the presenter below — which is what was producing the
        overlapping figures and flowcharts.
        """
        centre, w, h = self.stage_box()
        # ImageMobject is a Mobject, not a VMobject — .scale/.width work, but it
        # can never go in a VGroup (see CLAUDE.md).
        sx = (w * pad) / mob.width if mob.width > w * pad else 1.0
        sy = (h * pad) / mob.height if mob.height > h * pad else 1.0
        s = min(sx, sy)
        if s < 1.0:
            mob.scale(s)
        top, bot = centre[1] + h / 2, centre[1] - h / 2
        cy = top - (top - bot) * y
        cy = max(bot + mob.height / 2, min(top - mob.height / 2, cy))
        mob.move_to([0, cy, 0])
        return mob

    def rows(self, *mobs, buff=0.42, y=0.5):
        """Stack blocks with guaranteed spacing, then fit the lot."""
        g = VGroup(*mobs).arrange(DOWN, buff=buff)
        return self.place(g, y=y)

    def _hilite(self, line):
        """Words to colour, extended to whole words.

        Colouring a bare key splits the string wherever it matches, and a split
        inside a Devanagari cluster orphans the combining mark — "इलेक्ट्रॉन"
        matching inside "इलेक्ट्रॉनों" left the "ों" on its own and it rendered
        as a dotted circle. Matching the key but colouring the full word keeps
        every cluster intact.
        """
        out = {}
        for w in sorted(HILITE, key=len, reverse=True):
            if w not in line or any(w in k for k in out):
                continue
            colour = HILITE[w]
            for token in line.split():
                if w in token:
                    whole = token.strip(",।?!—:;")
                    if whole and not any(whole in k for k in out):
                        out[whole] = colour
        return out

    def _w(self, word, size):
        """Rendered width of one word, cached — wrapping measures, not counts."""
        if not hasattr(self, "_wcache"):
            self._wcache = {}
        k = (word, size)
        if k not in self._wcache:
            self._wcache[k] = Text(word, font=FONT, font_size=size,
                                   weight=FONT_W).width
        return self._wcache[k]

    def caption(self, text, size=CAPTION_SIZE):
        """Wrapped on measured width, with the load-bearing words picked out.

        Measured, not counted: a character-count wrap assumes every glyph is
        equally wide, which Devanagari conjuncts are not, so a long caption
        could reach the frame edge with no margin left.
        """
        limit = config.frame_width * CAPTION_W
        space = self._w(" ", size)
        lines, cur, cw = [], "", 0.0
        for word in text.split():
            ww = self._w(word, size)
            trial = cw + (space + ww if cur else ww)
            if cur and trial > limit:
                lines.append(cur); cur, cw = word, ww
            else:
                cur, cw = f"{cur} {word}".strip(), trial
        if cur:
            lines.append(cur)
        grp = VGroup()
        for ln in lines:
            grp.add(Text(ln, font=FONT, font_size=size, color=INK,
                         weight=FONT_W, t2c=self._hilite(ln)))
        grp.arrange(DOWN, buff=0.16)
        # Deliberately NOT scaled to fit. Scaling made every long caption
        # smaller than every short one, so the type size jumped around all
        # video. A caption that needs more room takes another line instead;
        # the wrap width above is what keeps it inside the frame.
        # Top 10% of the frame stays empty. Anchoring by the top edge keeps
        # that true whether the caption runs to one line or two — a fixed
        # centre let the taller ones bleed off the top.
        grp.move_to(norm_point(0.5, CAPTION_TOP))
        grp.shift(DOWN * grp.height / 2)
        return grp

    # --- timing -------------------------------------------------------- #
    def cue(self, i, caption=True, keep=False):
        """Advance to cue `i`, clearing the stage unless `keep=True`.

        Clearing is automatic and opt-out, not opt-in. Forgetting one
        `clear_stage()` was what put the iron bar on top of the word equation —
        the failure mode of opt-in clearing is a silent overlap, so the default
        is now the safe one.
        """
        if TEST_CUES and i >= TEST_CUES:
            raise _StopScene
        c = TIMING[i]
        if not keep:
            self.clear_stage()
        # A cue asking for no caption owns the screen — the question card is
        # the visual, and a caption over it is clutter.
        if not caption:
            nxt = TIMING[i + 1]["start"] if i + 1 < len(TIMING) else CLIP_END
            self._pending = [l for l in self._pending if l["start"] >= nxt]
        self.at(c["start"] - 0.30)
        self._cue_i = i
        if self._pending:
            self._line(self._pending.pop(0)["text"])

    def _line(self, text):
        """Swap in one caption line.

        Calls Scene.play directly: self.play is overridden to flush due lines
        first, and going through it here would recurse.
        """
        new = self.caption(text)
        if self.caption_mob is None:
            super().play(FadeIn(new, shift=DOWN * 0.10), run_time=0.22)
        else:
            old = self.caption_mob
            super().play(FadeOut(old, shift=UP * 0.10),
                         FadeIn(new, shift=DOWN * 0.10), run_time=0.22)
            self.remove(old)      # FadeOut leaves it in the scene otherwise
        self.caption_mob = new

    def _clear_caption(self):
        """Take the caption down when its sentence has finished being spoken.

        Without this a line stays up until the next one replaces it, so it hangs
        through every pause between sentences — which reads as the caption being
        out of sync even though its start was right.
        """
        if self.caption_mob is None:
            return
        old = self.caption_mob
        self.caption_mob = None
        super().play(FadeOut(old, shift=UP * 0.08), run_time=0.20)
        self.remove(old)

    def _expire(self, upto):
        """Drop the current caption if it has outlived its line and the next
        line is not due yet."""
        end = getattr(self, "_cap_end", None)
        if self.caption_mob is None or end is None or upto < end:
            return
        nxt = self._pending[0]["start"] if self._pending else None
        # only bother if the screen would otherwise sit on a stale line
        if nxt is None or nxt - end > 0.45:
            gap = end - self.time
            if gap > 0.02:
                self.wait(gap)
            self._clear_caption()
            self._cap_end = None

    def _due(self, upto=None):
        """Show every caption line whose moment has arrived."""
        limit = self.time if upto is None else upto
        while True:
            self._expire(limit)
            if not (self._pending and self._pending[0]["start"] <= limit + 1e-3):
                break
            nxt = self._pending.pop(0)
            gap = nxt["start"] - self.time
            if gap > 0.02:
                self.wait(gap)
            self._line(nxt["text"])
            self._cap_end = nxt.get("end")

    def play(self, *args, **kwargs):
        # An animation must not swallow a line that falls due while it runs.
        self._due()
        super().play(*args, **kwargs)

    def at(self, t):
        self._due(t)
        left = t - self.time
        if left > 0.02:
            self.wait(left)

    def hold(self):
        i = getattr(self, "_cue_i", 0)
        self.at(TIMING[i + 1]["start"] - 0.30 if i + 1 < len(TIMING) else CLIP_END)

    def clear_stage(self, rt=0.4):
        keep = {self.caption_mob, self.background}
        if self.chroma_zone is not None:
            keep.add(self.chroma_zone)
        doomed = [m for m in self.mobjects if m not in keep]
        if doomed:
            self.play(*[FadeOut(m) for m in doomed], run_time=rt)

    # --- pieces -------------------------------------------------------- #
    def iron_bar(self, w=3.4, h=1.0, color=IRON):
        bar = RoundedRectangle(width=w, height=h, corner_radius=0.12,
                               fill_color=color, fill_opacity=1, stroke_width=0)
        sheen = Line(bar.get_left() + RIGHT * 0.20 + UP * 0.20,
                     bar.get_right() + LEFT * 0.20 + UP * 0.20)
        sheen.set_stroke("#FFFFFF", 3, opacity=0.30)
        return VGroup(bar, sheen)

    def rust_patches(self, bar, n=10, seed=3, palette=(RUST, RUST_L)):
        rng = np.random.default_rng(seed)
        g, b = VGroup(), bar[0]
        for _ in range(n):
            r = rng.uniform(0.10, 0.26)
            x = rng.uniform(b.get_left()[0] + 0.28, b.get_right()[0] - 0.28)
            y = rng.uniform(b.get_bottom()[1] + 0.14, b.get_top()[1] - 0.14)
            g.add(VGroup(*[
                Circle(radius=r * rng.uniform(0.5, 1.0),
                       fill_color=palette[int(rng.integers(len(palette)))],
                       fill_opacity=1, stroke_width=0)
                .move_to([x + rng.uniform(-r, r), y + rng.uniform(-r * 0.6, r * 0.6), 0])
                for _ in range(3)]))
        return g

    def chip(self, txt, col, size=30):
        t = self.hindi(txt, size=size, color=INK)
        box = RoundedRectangle(width=t.width + 0.50, height=t.height + 0.42,
                               corner_radius=0.14, stroke_color=col,
                               stroke_width=4, fill_opacity=0.12, fill_color=col)
        return VGroup(box, t)

    # ------------------------------------------------------------------ #
    def construct(self):
        register_fonts()
        self.caption_mob = None
        self._pending = list(LINES)
        self._cap_end = None
        try:
            self._build()
        except _StopScene:
            pass

    def _build(self):

        # ============ cue 0 — QUESTION CARD, no caption ================== #
        self.cue(0, caption=False)
        qtext = ("संक्षारण किसे कहते हैं? इसे प्रभावित करने वाले तीन कारकों को "
                 "लिखकर इससे बचाव के कोई तीन उपाय लिखिए।")
        words, ql, cur = qtext.split(), [], ""
        for w in words:
            if len(f"{cur} {w}".strip()) > 32 and cur:
                ql.append(cur); cur = w
            else:
                cur = f"{cur} {w}".strip()
        ql.append(cur)

        qblock = VGroup(*[self.hindi(l, size=40, color=INK) for l in ql])
        qblock.arrange(DOWN, buff=0.28, aligned_edge=LEFT)
        mw = config.frame_width * 0.84
        if qblock.width > mw:
            qblock.scale(mw / qblock.width)

        marks = VGroup(self.hindi("अंक", size=25, color=DIM),
                       self.hindi("4", size=46, color=GOLD)).arrange(DOWN, buff=0.12)
        years = VGroup(self.hindi("वर्ष", size=25, color=DIM),
                       self.hindi("2025", size=46, color=GOLD)).arrange(DOWN, buff=0.12)
        meta = VGroup(marks, years).arrange(RIGHT, buff=1.05, aligned_edge=UP)
        rule = Line(LEFT, RIGHT).set_stroke(GOLD, 4).set_width(meta.width * 1.06)

        card = VGroup(qblock, rule, meta).arrange(DOWN, buff=0.62)
        qblock.align_to(card, LEFT)                      # question left-aligned
        rule.align_to(card, RIGHT)
        meta.align_to(card, RIGHT)                       # weightage + years right
        self.place(card, y=0.42)

        self.play(LaggedStart(*[FadeIn(l, shift=RIGHT * 0.25) for l in qblock],
                              lag_ratio=0.22), run_time=1.7)
        self.play(GrowFromEdge(rule, RIGHT), run_time=0.5)
        self.play(FadeIn(meta, shift=UP * 0.15), run_time=0.8)
        self.hold()
        self.play(FadeOut(card), run_time=0.45)

        # ============ cue 1 — captions begin ============================ #
        self.cue(1)
        self.hold()

        # ============ cues 2-3 — what corrosion is ====================== #
        self.cue(2)
        bar = self.place(self.iron_bar(), y=0.42)
        self.play(FadeIn(bar, shift=UP * 0.15), run_time=0.7)
        self.hold()

        # keep=True: the clean bar from cue 2 stays and rusts in place. Auto-
        # clear would wipe it and redraw, which read as the iron vanishing and
        # a different, already-rusted bar appearing.
        self.cue(3, keep=True)
        gases = VGroup(self.hindi("O₂", size=30, color=AQUA),
                       self.hindi("CO₂", size=30, color=AQUA),
                       self.hindi("H₂O", size=30, color=AQUA)
                       ).arrange(RIGHT, buff=0.75).next_to(bar, UP, buff=0.80)
        self.play(LaggedStart(*[FadeIn(g, shift=DOWN * 0.2) for g in gases],
                              lag_ratio=0.18), run_time=0.9)
        self.play(LaggedStart(*[GrowFromCenter(b) for b in self.rust_patches(bar)],
                              lag_ratio=0.10), run_time=2.0)
        self.hold()

        # ============ cues 4-5 — the word equation ====================== #
        self.cue(4)
        self.hold()

        self.cue(5)
        row = VGroup(self.chip("धातु", IRON), self.hindi("+", size=34, color=DIM),
                     self.chip("गैसें", AQUA), self.hindi("+", size=34, color=DIM),
                     self.chip("नमी", AQUA)).arrange(RIGHT, buff=0.30)
        arrow = MathTex(r"\Downarrow", color=GOLD).scale(1.5)
        res = self.chip("संक्षारण", RUST_L, size=34)
        eq = VGroup(row, arrow, res).arrange(DOWN, buff=0.40)
        self.place(eq, y=0.50)
        self.play(LaggedStart(*[FadeIn(m, shift=UP * 0.12) for m in row],
                              lag_ratio=0.16), run_time=1.1)
        self.play(GrowFromCenter(arrow), run_time=0.35)
        self.play(FadeIn(res, scale=1.08), run_time=0.5)
        self.hold()

        # ============ cue 6 — the everyday example, as a photograph ===== #
        # Vector shapes only approximate rust. The colour, the flaking and the
        # way it grows from patches ARE the teaching content here, so this beat
        # uses a generated image instead of drawn shapes.
        self.cue(6)
        nail = ImageMobject(str(_Path(ASSET_ROOT) / IMAGES["rusty_nail"]))
        nail.height = 3.2
        self.place(nail, y=0.46)
        self.play(FadeIn(nail, scale=1.04), run_time=0.9)
        self.play(nail.animate.scale(1.06), run_time=1.2, rate_func=there_and_back)
        self.hold()

        # ============ cue 7 — "three factors" announced ================= #
        self.cue(7)
        self.hold()

        # ============ cue 8 — factor 1: reactivity ====================== #
        self.cue(8)
        metals = VGroup()
        for nm, col in [("Zn", ZINC), ("Fe", IRON), ("Cu", "#B87333")]:
            b = RoundedRectangle(width=1.2, height=1.55, corner_radius=0.10,
                                 fill_color=col, fill_opacity=1, stroke_width=0)
            metals.add(VGroup(b, self.hindi(nm, size=28).next_to(b, DOWN, buff=0.22)))
        metals.arrange(RIGHT, buff=0.80)
        self.place(metals, y=0.34)
        speed = Arrow(metals.get_corner(DL) + DOWN * 0.80 + LEFT * 0.1,
                      metals.get_corner(DR) + DOWN * 0.80 + RIGHT * 0.1,
                      buff=0, color=WARN, stroke_width=6)
        sl = self.hindi("क्रियाशीलता घटती है", size=25, color=WARN)
        sl.next_to(speed, DOWN, buff=0.22)
        self.play(LaggedStart(*[FadeIn(m, shift=UP * 0.15) for m in metals],
                              lag_ratio=0.18), run_time=1.0)
        self.play(GrowArrow(speed), FadeIn(sl), run_time=0.6)
        self.hold()

        # ============ cue 9 — factor 2: impurities inside the metal ===== #
        self.cue(9)
        b2 = self.place(self.iron_bar(w=3.6, h=1.3), y=0.40)
        rng = np.random.default_rng(5)
        specks = VGroup(*[
            Circle(radius=rng.uniform(0.05, 0.09), fill_color="#39414D",
                   fill_opacity=1, stroke_width=0)
            .move_to([rng.uniform(b2[0].get_left()[0] + 0.22, b2[0].get_right()[0] - 0.22),
                      rng.uniform(b2[0].get_bottom()[1] + 0.16, b2[0].get_top()[1] - 0.16), 0])
            for _ in range(14)])
        self.play(FadeIn(b2), run_time=0.5)
        self.play(LaggedStart(*[GrowFromCenter(s) for s in specks],
                              lag_ratio=0.06), run_time=1.0)
        self.play(LaggedStart(*[GrowFromCenter(p)
                                for p in self.rust_patches(b2, n=12, seed=9)],
                              lag_ratio=0.07), run_time=1.4)
        self.hold()

        # ============ cue 10 — factor 3: environment ==================== #
        self.cue(10)
        b3 = self.place(self.iron_bar(w=3.0), y=0.50)
        ring = VGroup()
        for i, tag in enumerate(["हवा", "नमी", "गैसें", "लवण"]):
            a = i * TAU / 4 + PI / 4
            ring.add(self.hindi(tag, size=27, color=AQUA).move_to(
                b3.get_center() + np.array([np.cos(a) * 2.7, np.sin(a) * 1.55, 0])))
        self.play(FadeIn(b3), run_time=0.4)
        self.play(LaggedStart(*[FadeIn(t, scale=1.15) for t in ring],
                              lag_ratio=0.15), run_time=1.0)
        self.play(LaggedStart(*[GrowFromCenter(p)
                                for p in self.rust_patches(b3, n=9, seed=13)],
                              lag_ratio=0.08), run_time=1.3)
        self.hold()

        # ============ cue 11 — the three factors together =============== #
        self.cue(11)
        three = VGroup(self.chip("प्रकृति", WARN, 28),
                       self.chip("अशुद्धियाँ", GOLD, 28),
                       self.chip("वातावरण", AQUA, 28)).arrange(DOWN, buff=0.34)
        self.place(three, y=0.50)
        self.play(LaggedStart(*[FadeIn(c, shift=RIGHT * 0.2) for c in three],
                              lag_ratio=0.22), run_time=1.1)
        self.hold()

        # ============ cue 12 — "three remedies" announced =============== #
        self.cue(12)
        self.hold()

        # ============ cue 13 — barrier: an unbroken layer =============== #
        self.cue(13)
        b4 = self.place(self.iron_bar(w=3.4), y=0.46)
        self.play(FadeIn(b4), run_time=0.45)
        coat = RoundedRectangle(width=3.74, height=1.36, corner_radius=0.14,
                                fill_color=PAINT, fill_opacity=0.48,
                                stroke_width=3, stroke_color=PAINT)
        coat.move_to(b4.get_center())
        self.play(FadeIn(coat, shift=DOWN * 0.3), run_time=0.9)
        self.hold()

        # ============ cue 14 — sacrificial protection =================== #
        self.cue(14)
        b5 = self.place(self.iron_bar(w=3.2), y=0.38)
        zinc = RoundedRectangle(width=3.52, height=1.38, corner_radius=0.14,
                                fill_color=ZINC, fill_opacity=0.92, stroke_width=0)
        zinc.move_to(b5.get_center()).set_z_index(-1)
        self.play(FadeIn(zinc), FadeIn(b5), run_time=0.7)
        self.play(LaggedStart(*[GrowFromCenter(p) for p in self.rust_patches(
            VGroup(zinc), n=9, seed=11, palette=("#6E8DA6", "#5B7A93"))],
            lag_ratio=0.10), run_time=1.5)
        self.hold()

        # ============ cue 15 — galvanisation: zinc goes, iron survives == #
        self.cue(15, keep=True)      # the zinc bar carries over
        safe = VGroup(self.hindi("लोहा सुरक्षित", size=30, color=OK),
                      self.hindi("✓", size=40, color=OK)).arrange(RIGHT, buff=0.26)
        safe.next_to(zinc, DOWN, buff=0.55)
        self.play(FadeIn(safe, scale=1.1), run_time=0.7)
        self.hold()

        # ============ cue 16 — electroplating: object is the cathode ==== #
        self.cue(16)
        tank = VGroup(Line([-2.1, 1.05, 0], [-2.1, -1.05, 0]),
                      Line([-2.1, -1.05, 0], [2.1, -1.05, 0]),
                      Line([2.1, -1.05, 0], [2.1, 1.05, 0])).set_stroke(DIM, 5)
        bath = Rectangle(width=4.1, height=1.6, fill_color="#2E6FA8",
                         fill_opacity=0.34, stroke_width=0).move_to([0, -0.26, 0])
        obj = Rectangle(width=0.32, height=1.55, fill_color=IRON,
                        fill_opacity=1, stroke_width=0).move_to([1.05, -0.18, 0])
        src = Rectangle(width=0.32, height=1.55, fill_color=ZINC,
                        fill_opacity=1, stroke_width=0).move_to([-1.05, -0.18, 0])
        wire = VMobject().set_points_as_corners(
            [src.get_top(), [-1.05, 1.85, 0], [1.05, 1.85, 0], obj.get_top()]
        ).set_stroke(DIM, 4)
        pbar = Line([-0.18, 1.50, 0], [-0.18, 2.20, 0]).set_stroke(WARN, 7)
        nbar = Line([0.18, 1.64, 0], [0.18, 2.06, 0]).set_stroke(AQUA, 7)
        plate = Rectangle(width=0.15, height=1.55, fill_color="#D8DEE9",
                          fill_opacity=1, stroke_width=0).next_to(obj, LEFT, buff=0.0)
        nl = self.hindi("वस्तु = कैथोड (−)", size=26, color=AQUA)
        cell = VGroup(tank, bath, src, obj, plate, wire, pbar, nbar)
        nl.next_to(cell, DOWN, buff=0.36)
        self.place(VGroup(cell, nl), y=0.50)
        self.play(Create(tank), FadeIn(bath), run_time=0.6)
        self.play(FadeIn(src), FadeIn(obj), Create(wire),
                  FadeIn(pbar), FadeIn(nbar), run_time=0.8)
        self.play(FadeIn(plate), FadeIn(nl), run_time=0.7)
        self.hold()

        # ============ cue 17 — the one thing to remember ================ #
        self.cue(17)
        keys = VGroup(
            VGroup(self.hindi("3 कारक", size=32, color=GOLD),
                   self.hindi("प्रकृति · अशुद्धियाँ · वातावरण", size=26, color=DIM)
                   ).arrange(DOWN, buff=0.18),
            VGroup(self.hindi("3 उपाय", size=32, color=OK),
                   self.hindi("रोधिका · समर्पित बचाव · प्लेटिंग", size=26, color=DIM)
                   ).arrange(DOWN, buff=0.18),
        ).arrange(DOWN, buff=0.68)
        self.place(keys, y=0.48)
        self.play(LaggedStart(*[FadeIn(k, shift=UP * 0.14) for k in keys],
                              lag_ratio=0.25), run_time=1.2)
        self.hold()

        for i in (18, 19):
            self.cue(i)
            self.hold()

        # ============ cue 20 — sign-off ================================= #
        self.cue(20)
        end = VGroup(self.hindi("अरिविहान", size=56, color=GOLD),
                     self.hindi("उन्नति बैच", size=34, color=INK)
                     ).arrange(DOWN, buff=0.28)
        self.place(end, y=0.46)
        self.play(FadeIn(end, scale=1.06), run_time=0.8)
        self.hold()
